[project]
name = "application-package-patterns"
version = "1.0.0"

[build]
engine = "cluster"

[build.local]
runtime="docker"
registry="cr.terradue.com/earthquake-monitoring"

[build.cluster]
namespace = "eoap-application-package-patterns"
serviceAccount = "kaniko-sa"
registry = "cr.terradue.com/earthquake-monitoring"
secret = "kaniko-secret"

[tools.clt]
context = "vegetation-indexes"
path = "cwl-workflow/pattern-1.cwl#clt"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-1.cwl"

[[workflows.tests]]
name = "pattern-1-test"
description = "Test case for pattern-1"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-1"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-1"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"

[[workflows]]
path = "wrapped-cwl-workflow/pattern-2.cwl"

[[workflows.tests]]
name = "pattern-2-test"
description = "Test case for pattern-2"

[workflows.tests.params]
item_1 = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
item_2 = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC09_L2SP_042033_20231015_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-2"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-2"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"

[[workflows]]
path = "wrapped-cwl-workflow/pattern-3.cwl"

[[workflows.tests]]
name = "pattern-3-test"
description = "Test case for pattern-3"

[workflows.tests.params]
items = [{"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" },
         {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC09_L2SP_042033_20231015_02_T1" }]
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-3"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-3"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-4.cwl"

[[workflows.tests]]
name = "pattern-4-test"
description = "Test case for pattern-4"

[workflows.tests.params]
items = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-4"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-4"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-5.cwl"

[[workflows.tests]]
name = "pattern-5-test"
description = "Test case for pattern-5"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-5"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-5"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-6.cwl"

[[workflows.tests]]
name = "pattern-6-test"
description = "Test case for pattern-6"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-6"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-6"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"

[[workflows]]
path = "wrapped-cwl-workflow/pattern-7.cwl"

[[workflows.tests]]
name = "pattern-7-test-optional-input-set"
description = "Test case for pattern-7"

[workflows.tests.params]
item_1 = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
item_2 = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC09_L2SP_042033_20231015_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-7"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-7"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"

[[workflows.tests]]
name = "pattern-7-test-optional-input-not-set"
description = "Test case for pattern-7"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-7"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-7"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"



[[workflows]]
path = "wrapped-cwl-workflow/pattern-8.cwl"

[[workflows.tests]]
name = "pattern-8-test"
description = "Test case for pattern-8"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-8"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-8"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-9.cwl"

[[workflows.tests]]
name = "pattern-9-test"
description = "Test case for pattern-9"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-9"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-9"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-10.cwl"

[[workflows.tests]]
name = "pattern-10-test"
description = "Test case for pattern-10"

[workflows.tests.params]
item = {"class" = "https://raw.githubusercontent.com/eoap/schemas/main/url.yaml#URL", "href" = "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1" }
aoi = "-118.985,38.432,-118.183,38.938"
bands = ["green", "nir08"]
epsg = "EPSG:4326"

another_input = "a_value"

s3_bucket = "results"
sub_path = "pattern-10"
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "us-east-1"
endpoint_url = "http://eoap-application-package-patterns-localstack:4566"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-10"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"