version: '3'

tasks:

  stage:
    desc: 'Stage-in data'
    cmds:
      - |
        cd stage-in
        hatch run stage-in --output-dir ../data "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1"
        hatch run stage-in --output-dir ../data "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC09_L2SP_042033_20231015_02_T1"
    silent: false

  pattern-1:
    desc: 'Run pattern 1'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-1 \
          --input-item ../data/LC09_L2SP_042033_20231015_02_T1 \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false

  pattern-2:
    desc: 'Run pattern 2'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-2 \
          --input-item-1 ../data1/LC08_L2SP_042033_20231007_02_T1/ \
          --input-item-2 ../data1/LC09_L2SP_042033_20231015_02_T1/  \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false
  
  pattern-3:
    desc: 'Run pattern 3'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-3 \
          --input-item ../data1/LC08_L2SP_042033_20231007_02_T1/ \
          --input-item ../data1/LC09_L2SP_042033_20231015_02_T1/  \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false

  pattern-4:
    desc: 'Run pattern 4'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-4 \
          --input-item ../data1/LC08_L2SP_042033_20231007_02_T1/ \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
    silent: false