version: '3'

tasks:

  build:
    desc: 'Build the container'
    cmds:
      - |
        cd vegetation-indexes
        docker build -t vegetation-indexes:latest .
    silent: false

  stage:
    desc: 'Stage-in the Landsat data'
    cmds:
      - |
        cd stage-in
        hatch run stage-in --output-dir ../data "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SP_042033_20231007_02_T1"
        hatch run stage-in --output-dir ../data "https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC09_L2SP_042033_20231015_02_T1"
    silent: false

  pattern-1:
    desc: |
      Run pattern 1: one input parameter of type `Directory`, one output parameter of type `Directory`
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-1 \
          --input-item ../data/LC09_L2SP_042033_20231015_02_T1 \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false

  pattern-1-cwl:
    desc: |
      Run pattern 1 using CWL: one input parameter of type `Directory`, one output parameter of type `Directory`
    cmds:
      - defer: rm -fv .params.yaml
      - |
        echo 'item: {"class": "Directory", "path": "data/LC09_L2SP_042033_20231015_02_T1"}' > .params.yaml
        echo 'aoi: "-118.985,38.432,-118.183,38.938"' >> .params.yaml
        echo 'epsg: "EPSG:4326"' >> .params.yaml
        echo 'band: ["green", "nir08"]' >> .params.yaml
        cwltool cwl-workflow/pattern-1.cwl .params.yaml
    silent: false

  pattern-2:
    desc: 'Run pattern 2'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-2 \
          --input-item-1 ../data/LC08_L2SP_042033_20231007_02_T1/ \
          --input-item-2 ../data/LC09_L2SP_042033_20231015_02_T1/  \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false
  
  pattern-2-cwl:
    desc: |
      Run pattern 2 using CWL: two input parameters of type `Directory` and one output parameter of type `Directory`
    cmds:
      - defer: rm -fv .params.yaml
      - |
        echo 'item_1: {"class": "Directory", "path": "data/LC08_L2SP_042033_20231007_02_T1"}' > .params.yaml
        echo 'item_2: {"class": "Directory", "path": "data/LC09_L2SP_042033_20231015_02_T1"}' >> .params.yaml
        echo 'aoi: "-118.985,38.432,-118.183,38.938"' >> .params.yaml
        echo 'epsg: "EPSG:4326"' >> .params.yaml
        echo 'band: ["green", "nir08"]' >> .params.yaml
        cwltool cwl-workflow/pattern-2.cwl .params.yaml
    silent: false

  pattern-3:
    desc: 'Run pattern 3'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-3 \
          --input-item ../data/LC08_L2SP_042033_20231007_02_T1/ \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false

  pattern-3-cwl:
    desc: 'Run pattern 3 using CWL'
    cmds:
      - defer: rm -fv .params.yaml
      - |
        echo 'items:' > .params.yaml
        echo '- {"class": "Directory", "path": "data/LC09_L2SP_042033_20231015_02_T1"}' >> .params.yaml
        echo '- {"class": "Directory", "path": "data/LC08_L2SP_042033_20231007_02_T1"}' >> .params.yaml
        echo 'aoi: "-118.985,38.432,-118.183,38.938"' >> .params.yaml
        echo 'epsg: "EPSG:4326"' >> .params.yaml
        cwltool cwl-workflow/pattern-3.cwl .params.yaml
    silent: false


  pattern-4:
    desc: 'Run pattern 4'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-4 \
          --input-item ../data/LC08_L2SP_042033_20231007_02_T1/ \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
    silent: false

  pattern-4-cwl:
    desc: 'Run pattern 4 using CWL'
    cmds:
      - defer: rm -fv .params.yaml
      - |
        echo 'item: {"class": "Directory", "path": "data/LC09_L2SP_042033_20231015_02_T1"}' > .params.yaml
        echo 'aoi: "-118.985,38.432,-118.183,38.938"' >> .params.yaml
        echo 'epsg: "EPSG:4326"' >> .params.yaml
        cwltool cwl-workflow/pattern-4.cwl .params.yaml
    silent: false

  pattern-7a:
    desc: |
      Run pattern 7a: one optional input parameter of type `Directory?` (set) and one output parameter of type `Directory'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-7 \
          --input-item-1 ../data/LC08_L2SP_042033_20231007_02_T1/ \
          --input-item-2 ../data/LC09_L2SP_042033_20231015_02_T1/  \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false

  pattern-7a-cwl:
    desc: |
      Run pattern 7a using CWL: one optional input parameter of type `Directory?` (set) and one output parameter of type `Directory`
    cmds:
      - defer: rm -fv .params.yaml
      - |
        echo 'item_1: {"class": "Directory", "path": "data/LC08_L2SP_042033_20231007_02_T1"}' > .params.yaml
        echo 'item_2: {"class": "Directory", "path": "data/LC09_L2SP_042033_20231015_02_T1"}' >> .params.yaml
        echo 'aoi: "-118.985,38.432,-118.183,38.938"' >> .params.yaml
        echo 'epsg: "EPSG:4326"' >> .params.yaml
        echo 'band: ["green", "nir08"]' >> .params.yaml
        cwltool cwl-workflow/pattern-7.cwl .params.yaml
    silent: false

  pattern-7b:
    desc: |
      Run pattern 7b: one optional input parameter of type `Directory?` (not set) and one output parameter of type `Directory'
    cmds:
      - |
        cd vegetation-indexes
        hatch run \
          vegetation-index pattern-7 \
          --input-item-1 ../data/LC08_L2SP_042033_20231007_02_T1/ \
          --aoi="-118.985,38.432,-118.183,38.938" \
          --epsg "EPSG:4326" \
          --band green \
          --band nir08
    silent: false

  pattern-7b-cwl:
    desc: |
      Run pattern 7b using CWL: one optional input parameter of type `Directory?` (not set) and one output parameter of type `Directory`
    cmds:
      - defer: rm -fv .params.yaml
      - |
        echo 'item_1: {"class": "Directory", "path": "data/LC08_L2SP_042033_20231007_02_T1"}' > .params.yaml
        echo 'aoi: "-118.985,38.432,-118.183,38.938"' >> .params.yaml
        echo 'epsg: "EPSG:4326"' >> .params.yaml
        echo 'band: ["green", "nir08"]' >> .params.yaml
        cwltool cwl-workflow/pattern-7.cwl .params.yaml
    silent: false