[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stage-out"
dynamic = ["version"]
description = "Stage a STAC catalog out to S3-compatible storage."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Fabrice Brito", email = "fabrice.brito@terradue.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "boto3==1.35.36",
  "click",
  "pystac>=1.15.1",
]

[project.urls]
Documentation = "https://github.com/eoap/application-package-patterns#readme"
Issues = "https://github.com/eoap/application-package-patterns/issues"
Source = "https://github.com/eoap/application-package-patterns"

[tool.hatch.version]
path = "src/stage_out/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/stage_out tests}"

[tool.coverage.run]
source_pkgs = ["stage_out", "tests"]
branch = true
parallel = true
omit = [
  "src/stage_out/__about__.py",
]

[tool.coverage.paths]
stage_out = ["src/stage_out", "*/stage-out/src/stage_out"]
tests = ["tests", "*/stage-out/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[project.scripts]
stage-out = "stage_out.app:cli"
